In [111]:
import pennylane as qml
from pennylane import numpy as np

In [112]:
dev1 = qml.device('default.qubit', wires=1)

@qml.qnode(dev1)
def circuit(params):
    qml.RX(params[0], wires=0)
    qml.RY(params[1], wires=0)
    return qml.expval(qml.PauliZ(0))

In [113]:
print(circuit([0.54, 0.12]))

0.8515405859048367


In [114]:
@qml.qnode(dev1)
def circuit(params):
    qml.RX(params[0], wires=0)
    qml.RY(params[1], wires=0)
    return qml.probs(wires=0)

print(circuit([0.54, 0.12]))

[0.92577029 0.07422971]


In [115]:
# dcircuit = qml.grad(circuit, argnum=0)
# print(dcircuit([0.54, 0.12]))

In [116]:
def cost(x):
    return circuit(x)

init_params = np.array([0.011, 0.012], requires_grad=True)
print(cost(init_params))

[9.99933753e-01 6.62470850e-05]


In [117]:
dev_gaussian = qml.device("default.gaussian", wires=1)

@qml.qnode (dev_gaussian) 
def mean_photon_gaussian(mag_alpha, phase_alpha, phi):
    qml.Displacement(mag_alpha, phase_alpha, wires=0) 
    qml.Rotation (phi, wires=0) 
    return qml.expval(qml.NumberOperator(0))

In [118]:
def cost(params):
    return (mean_photon_gaussian(params[0], params[1], params[2]) - 1.0) ** 2

init_params = np.array([0.015, 0.02, 0.005], requires_grad=True)
print(cost(init_params))

0.9995500506249999


In [119]:
# initialise the optimizer 
opt = qml.GradientDescentOptimizer(stepsize=0.4)

# set the number of steps 
steps = 100 
# set the initial parameter values 
params = init_params

for i in range(steps):
    # update the circuit parameters 
    params = opt.step(cost, params)

    if (i + 1) % 5 == 0:
        print("Cost after step {:5d}: {: .7f}".format(i + 1, cost(params)))

print("Optimized rotation angles: {}".format(params))

Cost after step     5:  0.3208685
Cost after step    10:  0.9999628
Cost after step    15:  0.5648670
Cost after step    20:  0.9996791
Cost after step    25:  0.1418484
Cost after step    30:  0.7655847
Cost after step    35:  0.1680231
Cost after step    40:  0.3898240
Cost after step    45:  0.9928800
Cost after step    50:  0.3548833
Cost after step    55:  0.0121444
Cost after step    60:  0.3890158
Cost after step    65:  0.9714638
Cost after step    70:  0.9999116
Cost after step    75:  0.2063307
Cost after step    80:  0.9860039
Cost after step    85:  0.0638332
Cost after step    90:  0.5363780
Cost after step    95:  0.8276998
Cost after step   100:  0.9978378
Optimized rotation angles: [0.03288923 0.02       0.005     ]


In [120]:
# initialise the optimizer 
opt = qml.GradientDescentOptimizer(stepsize=0.1)
# set the number of steps 
steps = 20 
# set the initial parameter values 
params = init_params

for i in range(steps):
    # update the circuit parameters 
    params = opt.step(cost, params)
    print("Cost after step {:5d}: {:8f}".format(i + 1, cost(params)))

print("Optimized mag_alpha: {:8f}".format(params[0])) 
print("Optimized phase_alpha: {:8f}".format(params[1])) 
print("Optimized phi: {:8f}".format(params[2]))

Cost after step     1: 0.999118
Cost after step     2: 0.998273
Cost after step     3: 0.996618
Cost after step     4: 0.993382
Cost after step     5: 0.987074
Cost after step     6: 0.974837
Cost after step     7: 0.951332
Cost after step     8: 0.907043
Cost after step     9: 0.826649
Cost after step    10: 0.690812
Cost after step    11: 0.490303
Cost after step    12: 0.258845
Cost after step    13: 0.083224
Cost after step    14: 0.013179
Cost after step    15: 0.001001
Cost after step    16: 0.000049
Cost after step    17: 0.000002
Cost after step    18: 0.000000
Cost after step    19: 0.000000
Cost after step    20: 0.000000
Optimized mag_alpha: 0.999994
Optimized phase_alpha: 0.020000
Optimized phi: 0.005000


In [121]:
# dev_fock = qml.device("strawberryfields.fock", wires=2, cutoff_dim=2)

# @qml.qnode(dev_fock, diff_method="parameter-shift") 
# def photon_redirection(params):
#     qml.FockState(1, wires=0) 
#     qml.Beamsplitter(params[0], params[1], wires=[0, 1]) 
#     return qml.expval(qml.NumberOperator(1))

In [122]:
# def cost(params):
#     return -photon_redirection(params)

# init_params = np.array([0.01, 0.01], requires_grad=True)
# print(cost(init_params))

In [123]:
# # initialise the optimizer 
# opt = qml.GradientDescentOptimizer(stepsize=0.4)

# # set the number of steps 
# steps = 100 
# # set the initial parameter values 
# params = init_params

# for i in range(steps):
#     # update the circuit parameters 
#     params = opt.step(cost, params)

#     if (i + 1) % 5 == 0:
#         print("Cost after step {:5d}: {: .7f}".format(i + 1, cost(params)))

# print("Optimized rotation angles: {}".format(params))

In [124]:
# # create the devices 
# dev_qubit = qml.device("default.qubit", wires=1) 
# dev_fock = qml.device("strawberryfields.fock", wires=2, cutoff_dim=10)

# @qml.qnode (dev_qubit) 
# def qubit_rotation (phi1, phi2):
#     """Qubit rotation QNode""" 
#     qml. RX(phi1, wires=0) 
#     qml. RY(phi2, wires=0) 
#     return qml.expval(qml.Pauliz(0))

# @qml.qnode (dev_fock, diff_method="parameter-shift") 
# def photon_redirection(params) :
#     """The photon redirection QNode""" 
#     qml.FockState(1, wires=0) 
#     qml.Beamsplitter(params[0], params[1], wires=[0, 1]) 
#     return qml.expval(qml.NumberOperator(1))

# def squared_difference(x, y):
#     """Classical node to compute the squared difference 
#     between two inputs"""
#     return np.abs(x - y) ** 2

In [125]:
# def cost(params, phi1=0.5, phi2=0.1):
#     """Returns the squared difference between the photon-redirection 
#     and qubit-rotation QNodes, for fixed values of the qubit rotation 
#     angles phi1 and phi2"""
#     qubit_result = qubit_rotation(phi1, phi2) 
#     photon_result = photon_redirection(params) 
#     return squared_difference(qubit_result, photon_result)

In [126]:
# # initialise the optimizer
# opt = qml.GradientDescentOptimizer (stepsize=0.4)
# # set the number of steps 
# steps = 100
# # set the initial parameter values
# params = np.array([0.01, 0.01], requires_grad=True)

# for i in range(steps):
#     # update the circuit parameters 
#     params = opt.step(cost, params)
#     if (i + 1) % 5 == 0:
#         print("Cost after step {:5d}: {: .7f}".format(i + 1, cost(params)))
        
# print("Optimized rotation angles: {}".format(params))

In [127]:
# result = [1.20671364, 0.01]
# print(photon_redirection(result))
# print(qubit_rotation(0.5, 0.1))

In [128]:
@qml.qnode(dev1)
def qcircuit(params):
    qml.RX(params[0], wires=0)
    qml.RY(params[1], wires=0)
    return qml.probs(wires=0)

print(qcircuit([0.54, 0.12]))

[0.92577029 0.07422971]


In [129]:
drawer = qml.draw(qcircuit)
print(drawer(params = [0.54, 0.12]))

0: ──RX(0.54)──RY(0.12)─┤  Probs


In [130]:
# Variational Classifiers

In [131]:
from pennylane.optimize import NesterovMomentumOptimizer

dev = qml.device("default.qubit", wires=4)

In [132]:
def layer(W):
    qml.Rot(W[0, 0], W[0, 1], W[0, 2], wires=0) 
    qml.Rot(W[1, 0], W[1, 1], W[1, 2], wires=1) 
    qml.Rot(W[2, 0], W[2, 1], W[2, 2], wires=2) 
    qml.Rot(W[3, 0], W[3, 1], W[3, 2], wires=3)

    qml.CNOT(wires=[0, 1]) 
    qml.CNOT(wires=[1, 2]) 
    qml.CNOT(wires=[2, 3]) 
    qml.CNOT(wires=[3, 0])

In [133]:
def statepreparation(x):
    qml.BasisState(x, wires=[0, 1, 2, 3])

@qml.qnode(dev)
def circuit(weights, x):
    
    statepreparation(x)

    for W in weights:
        layer(W)
    return qml.expval(qml.PauliZ(0))

In [134]:
def variational_classifier(weights, bias, x):
    return circuit(weights, x) + bias

def square_loss(labels, predictions):
    loss = 0
    for l, p in zip(labels, predictions):
        loss = loss + (l - p) ** 2
    loss = loss / len(labels)
    return loss

In [135]:
def accuracy(labels, predictions):
    loss = 0
    for l, p in zip(labels, predictions):
        if abs(l - p) < 1e-5:
            loss = loss + 1
    loss = loss / len(labels)
    return loss

def cost(weights, bias, X, Y):
    predictions = [variational_classifier(weights, bias, x) for x in X]
    return square_loss(Y, predictions)

In [136]:
data = np.loadtxt('parity.txt')
X = np.array(data[:, :-1], requires_grad=False)
Y = np.array(data[:, -1], requires_grad=False)
Y = Y * 2 - np.ones(len(Y)) # shift label from {0, 1} to {-1, 1}

for i in range(5):
    print("X = {}, Y = {:d}".format(X[i], int(Y[i])))
    
print("...")

X = [0. 0. 0. 0.], Y = -1
X = [0. 0. 0. 1.], Y = 1
X = [0. 0. 1. 0.], Y = -1
X = [0. 0. 1. 1.], Y = -1
X = [0. 1. 0. 0.], Y = 1
...


In [137]:
np.random.seed(0)
num_qubits = 4
num_layers = 2
weights_init = 0.01 * np.random.randn(num_layers, num_qubits, 3, requires_grad=True)
bias_init = np.array(0.0, requires_grad=True)

print(weights_init, bias_init)

[[[ 0.01764052  0.00400157  0.00978738]
  [ 0.02240893  0.01867558 -0.00977278]
  [ 0.00950088 -0.00151357 -0.00103219]
  [ 0.00410599  0.00144044  0.01454274]]

 [[ 0.00761038  0.00121675  0.00443863]
  [ 0.00333674  0.01494079 -0.00205158]
  [ 0.00313068 -0.00854096 -0.0255299 ]
  [ 0.00653619  0.00864436 -0.00742165]]] 0.0


In [138]:
opt = NesterovMomentumOptimizer(0.5)
batch_size = 5

weights = weights_init 
bias = bias_init 

for it in range(25):
    # Update the weights by one optimizer step 
    batch_index = np.random.randint(0, len(X), (batch_size,))
    X_batch = X[batch_index] 
    Y_batch = Y[batch_index] 
    weights, bias, _, _ = opt.step(cost, weights, bias, X_batch, Y_batch)
    # Compute accuracy 
    predictions = [np.sign(variational_classifier(weights, bias, x)) for x in X] 
    acc = accuracy(Y, predictions)
    print("Iter: {:5d} | Cost: {:0.7f} | Accuracy: {:0.7f} ".format(
        it + 1, cost(weights, bias, X, Y), acc))

Iter:     1 | Cost: 4.4033157 | Accuracy: 0.5625000 
Iter:     2 | Cost: 2.2725797 | Accuracy: 0.4375000 
Iter:     3 | Cost: 2.0090492 | Accuracy: 0.4375000 
Iter:     4 | Cost: 1.6826451 | Accuracy: 0.4375000 
Iter:     5 | Cost: 1.1116542 | Accuracy: 0.5625000 
Iter:     6 | Cost: 1.1706354 | Accuracy: 0.5625000 
Iter:     7 | Cost: 1.3254411 | Accuracy: 0.5625000 
Iter:     8 | Cost: 0.5796337 | Accuracy: 0.9375000 
Iter:     9 | Cost: 0.2304945 | Accuracy: 0.9375000 
Iter:    10 | Cost: 0.2620422 | Accuracy: 0.9375000 
Iter:    11 | Cost: 0.2925748 | Accuracy: 0.9375000 
Iter:    12 | Cost: 0.2987950 | Accuracy: 0.9375000 
Iter:    13 | Cost: 0.2776045 | Accuracy: 0.9375000 
Iter:    14 | Cost: 0.2306265 | Accuracy: 0.9375000 
Iter:    15 | Cost: 0.6677253 | Accuracy: 0.5625000 
Iter:    16 | Cost: 0.6016584 | Accuracy: 0.8125000 
Iter:    17 | Cost: 0.6462330 | Accuracy: 0.8125000 
Iter:    18 | Cost: 0.8851776 | Accuracy: 0.5625000 
Iter:    19 | Cost: 0.3543852 | Accuracy: 0.93